defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *defaults
  database: recidivism_visualizer_development

test:
  <<: *defaults
  database: recidivism_visualizer_test

production:
  <<: *defaults
  database: recidivism_visualizer_production
